### ISSUE TITLE
[Logo] ValueError('Cannot create group in read only mode.')

### ISSUE THREAD

**Issue by roricljy** [deepguider/DeepGuider#78]
When it is loading the trained model, `./model/keras_yolo3/logs/0001/trained_weights_final.h5` , it gives the following error:
```
Traceback (most recent call last):
  File "./../src/logo_recog/model/keras_yolo3/yolo.py", line 72, in generate
    self.yolo_model = load_model(model_path, compile=False)
  File "/work/venv/dg/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/work/venv/dg/lib/python3.6/site-packages/keras/engine/saving.py", line 221, in _deserialize_model
    model_config = f['model_config']
  File "/work/venv/dg/lib/python3.6/site-packages/keras/utils/io_utils.py", line 302, in __getitem__
    raise ValueError('Cannot create group in read only mode.')
ValueError: Cannot create group in read only mode.
```

**Comment by minnjung** [comment]
안녕하세요,
서울대학교 김건희 교수님 연구실의 김민정입니다.

기존에 발생했던 logo_recog의 실행 오류 관련된 문제를 모두 해결하였고,
Initialization 시간이 오래 걸리던 것을 1분 내외로 해결할 수 있도록 보완하였습니다.

한국 브랜드 recognition을 진행하는 부분에 있어서 아직 좋은 성능을 내기에는 다소 실험 데이터 정제와 보완이 필요해 보이지만 
테스트를 진행할 수 있도록 정리해서 github에 올려놓았으니 확인 부탁드립니다.

그리고 실제로 들어오는 image sample들을 좀 얻을 수 있을까요?
Image 사이즈나 상호 모양, 크기 등을 파악해서 recognition module을 보완하는데 참고할 수 있을 것 같습니다.

확인 부탁드립니다.
감사합니다.

김민정 드림
